from config import load_config
from finding_sources.harness_sto import discover_scan_id, get_scan_issues
from remediation_engine import generate_fix
from file_patcher import apply_fix
from git_client import create_branch, commit_changes, push_branch
from pr_client import create_pull_request


def summarize_issue(issue: dict) -> dict:
    occurrence = issue.get("occurrences", [{}])[0]

    return {
        "issue_id": issue.get("id"),
        "title": issue.get("title"),
        "severity": issue.get("severityCode"),
        "rule": issue.get("key"),
        "file": occurrence.get("fileName"),
        "line": occurrence.get("lineNumber"),
        "snippet": occurrence.get("codeSnippet"),
        "remediation": occurrence.get("remediationSteps")
        or issue.get("details", {}).get("remediationSteps"),
    }


def print_issue(summary: dict) -> None:
    print("=" * 80)
    print(f"Issue ID : {summary['issue_id']}")
    print(f"Severity : {summary['severity']}")
    print(f"Rule     : {summary['rule']}")
    print(f"File     : {summary['file']}")
    print(f"Line     : {summary['line']}")
    print(f"Title    : {summary['title']}")


def build_pr_description(scan_id: str, applied_fixes: list[dict]) -> str:
    lines = [
        "## Auto-remediation Summary",
        "",
        f"STO Scan ID: `{scan_id}`",
        "",
        "This PR/MR was generated by the remediation framework using security scan findings.",
        "",
        "### Applied Fixes",
        "",
    ]

    for fix in applied_fixes:
        lines.extend(
            [
                f"- File: `{fix['file']}`",
                f"  - Reason: {fix['reason']}",
                "",
            ]
        )

    lines.extend(
        [
            "### Review Notes",
            "",
            "- Developer review is required before merge.",
            "- Re-run the security scan after merge to validate remediation.",
        ]
    )

    return "\n".join(lines)


def main():
    config = load_config()

    scan_id = discover_scan_id(config)
    remediation_branch = config.remediation_branch or f"auto-remediate-{scan_id}"

    print("=" * 80)
    print("Autonomous Remediation Framework")
    print("=" * 80)
    print(f"Finding Provider     : {config.finding_provider}")
    print(f"Remediation Provider : {config.remediation_provider}")
    print(f"Repository Provider  : {config.repo_provider}")
    print(f"Local Repo Dir       : {config.local_repo_dir}")
    print(f"Execution ID         : {config.harness_execution_id}")
    print(f"Scan ID              : {scan_id}")
    print(f"Branch               : {remediation_branch}")
    print("=" * 80)

    create_branch(
        config.local_repo_dir,
        remediation_branch,
        config.base_branch,
    )

    issues = get_scan_issues(config, scan_id)

    print(f"Found {len(issues)} STO issues\n")

    applied_any_fix = False
    applied_fixes = []
    seen_fixes = set()

    for issue in issues:
        summary = summarize_issue(issue)
        print_issue(summary)

        fix = generate_fix(summary)

        if not fix:
            continue

        fix_key = (fix["file"], fix["old_code"], fix["new_code"])

        if fix_key in seen_fixes:
            print("Skipping duplicate fix.")
            continue

        seen_fixes.add(fix_key)

        print("\nGenerated Fix:")
        print(f"File   : {fix['file']}")
        print(f"Old    : {fix['old_code']}")
        print(f"New    : {fix['new_code']}")
        print(f"Reason : {fix['reason']}")

        applied = apply_fix(config.local_repo_dir, fix)

        print(f"Applied Fix: {applied}\n")

        if applied:
            applied_any_fix = True
            applied_fixes.append(fix)

    if not applied_any_fix:
        print("\nNo remediation was applied. Nothing to commit, push, or PR/MR.")
        return

    committed = commit_changes(
        config.local_repo_dir,
        "Auto-remediation for security findings",
    )

    if not committed:
        print("\nNo commit created. Skipping push and PR/MR.")
        return

    push_branch(config.local_repo_dir, remediation_branch)

    pr_description = build_pr_description(scan_id, applied_fixes)

    create_pull_request(
        source_branch=remediation_branch,
        target_branch=config.base_branch,
        title=config.pr_title,
        description=pr_description,
    )

    print("\nRemediation workflow completed successfully.")


if __name__ == "__main__":
    main()