import os
import requests

from remediation_engine import generate_fix
from file_patcher import apply_fix
from git_client import create_branch, commit_changes, push_branch
from pr_client import create_pull_request


HARNESS_BASE_URL = "https://app.harness.io"


def get_sto_issues(account_id: str, api_key: str, scan_id: str) -> list[dict]:
    url = f"{HARNESS_BASE_URL}/sto/api/v2/scans/{scan_id}/issues"
    headers = {"X-Api-Key": api_key}
    params = {"accountId": account_id}

    response = requests.get(url, headers=headers, params=params, timeout=30)
    response.raise_for_status()

    return response.json().get("issues", [])


def summarize_issue(issue: dict) -> dict:
    occurrence = issue.get("occurrences", [{}])[0]

    return {
        "issue_id": issue.get("id"),
        "title": issue.get("title"),
        "severity": issue.get("severityCode"),
        "rule": issue.get("key"),
        "file": occurrence.get("fileName"),
        "line": occurrence.get("lineNumber"),
        "snippet": occurrence.get("codeSnippet"),
        "remediation": occurrence.get("remediationSteps")
        or issue.get("details", {}).get("remediationSteps"),
    }


def print_issue(summary: dict) -> None:
    print("=" * 80)
    print(f"Issue ID : {summary['issue_id']}")
    print(f"Severity : {summary['severity']}")
    print(f"Rule     : {summary['rule']}")
    print(f"File     : {summary['file']}")
    print(f"Line     : {summary['line']}")
    print(f"Title    : {summary['title']}")


def build_pr_description(scan_id: str, applied_fixes: list[dict]) -> str:
    lines = [
        "## Auto-remediation Summary",
        "",
        f"STO Scan ID: `{scan_id}`",
        "",
        "This PR/MR was generated by the remediation agent using Harness STO scan findings.",
        "",
        "### Applied Fixes",
        "",
    ]

    for fix in applied_fixes:
        lines.extend(
            [
                f"- File: `{fix['file']}`",
                f"  - Reason: {fix['reason']}",
                "",
            ]
        )

    lines.extend(
        [
            "### Review Notes",
            "",
            "- Developer review is required before merge.",
            "- Re-run the STO scan after merge to validate remediation.",
        ]
    )

    return "\n".join(lines)


def main():
    account_id = os.environ["HARNESS_ACCOUNT_ID"]
    api_key = os.environ["HARNESS_API_KEY"]
    scan_id = os.environ["HARNESS_SCAN_ID"]

    repo_dir = os.environ.get(
        "LOCAL_REPO_DIR",
        r"C:\Users\keeva\Desktop\git\ai-remediation-poc",
    )

    base_branch = os.environ.get("BASE_BRANCH", "main")
    branch_name = os.environ.get(
        "REMEDIATION_BRANCH",
        f"auto-remediate-{scan_id}",
    )

    create_branch(repo_dir, branch_name, base_branch)

    issues = get_sto_issues(account_id, api_key, scan_id)

    print(f"Found {len(issues)} STO issues\n")

    applied_any_fix = False
    applied_fixes = []
    seen_fixes = set()

    for issue in issues:
        summary = summarize_issue(issue)
        print_issue(summary)

        fix = generate_fix(summary)

        if not fix:
            continue

        fix_key = (fix["file"], fix["old_code"], fix["new_code"])

        if fix_key in seen_fixes:
            print("Skipping duplicate fix.")
            continue

        seen_fixes.add(fix_key)

        print("\nGenerated Fix:")
        print(f"File   : {fix['file']}")
        print(f"Old    : {fix['old_code']}")
        print(f"New    : {fix['new_code']}")
        print(f"Reason : {fix['reason']}")

        applied = apply_fix(repo_dir, fix)

        print(f"Applied Fix: {applied}\n")

        if applied:
            applied_any_fix = True
            applied_fixes.append(fix)

    if not applied_any_fix:
        print("\nNo remediation was applied. Nothing to commit, push, or PR.")
        return

    committed = commit_changes(
        repo_dir,
        "Auto-remediation for STO findings",
    )

    if not committed:
        print("\nNo commit created. Skipping push and PR/MR.")
        return

    push_branch(repo_dir, branch_name)

    pr_title = os.environ.get(
        "PR_TITLE",
        "Auto-remediation for STO findings",
    )

    pr_description = build_pr_description(scan_id, applied_fixes)

    create_pull_request(
        source_branch=branch_name,
        target_branch=base_branch,
        title=pr_title,
        description=pr_description,
    )

    print("\nStep 6 completed successfully.")


if __name__ == "__main__":
    main()